language: python

os: linux

cache:
    directories:
        - "$HOME/.cache/pip"

git:
    quiet: true
    submodules: false

branches:
    only:
        - master

dist: bionic

services:
    - docker

python:
    - 3.7

before_install:
    - pip install --upgrade pip
    - pip install --upgrade setuptools
    - pip install "invenio-cli==0.16.0"
    - nvm install 13.14.0
    - ./scripts/before_install.sh

install:
    - invenio-cli install --pre

script:
    - ./scripts/run-tests.sh

# deploy:
#     - provider: codedeploy
#       revision_type: github
#       access_key_id: "$AWS_ACCESS_KEY_ID"
#       secret_access_key: "$AWS_SECRET_ACCESS_KEY"
#       application: GEO-Knowledge-Hub
#       deployment_group: GEO-Knowledge-Hub-DeploymentGroup
#       region: us-east-1
#       on:
#           repo: geo-knowledge-hub/geo-knowledge-hub
#           branch: master
#       wait_until_deployed: true
#       skip_cleanup: true
