name: build

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  Tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node 14.x
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install "invenio-cli==0.23.1"

      - name: Prepare InvenioRDM config files
        run: |
          ./scripts/before_install.sh

      - name: Install GEO-Knowledge Hub Dependencies
        run: |
          invenio-cli install